%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-rmw-fastrtps-dynamic-cpp
Version:        9.3.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmw_fastrtps_dynamic_cpp package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-ament-cmake
Requires:       ros-kilted-fastcdr
Requires:       ros-kilted-fastdds
Requires:       ros-kilted-rcpputils
Requires:       ros-kilted-rcutils
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rmw-dds-common
Requires:       ros-kilted-rmw-fastrtps-shared-cpp
Requires:       ros-kilted-rosidl-runtime-c
Requires:       ros-kilted-rosidl-typesupport-introspection-c
Requires:       ros-kilted-rosidl-typesupport-introspection-cpp
Requires:       ros-kilted-tracetools
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake-ros-core
BuildRequires:  ros-kilted-fastcdr
BuildRequires:  ros-kilted-fastdds
BuildRequires:  ros-kilted-rcpputils
BuildRequires:  ros-kilted-rcutils
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-rmw-dds-common
BuildRequires:  ros-kilted-rmw-fastrtps-shared-cpp
BuildRequires:  ros-kilted-rosidl-runtime-c
BuildRequires:  ros-kilted-rosidl-typesupport-introspection-c
BuildRequires:  ros-kilted-rosidl-typesupport-introspection-cpp
BuildRequires:  ros-kilted-tracetools
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rmw-implementation-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
BuildRequires:  ros-kilted-osrf-testing-tools-cpp
BuildRequires:  ros-kilted-test-msgs
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rmw-implementation-packages(all)
%endif

%description
Implement the ROS middleware interface using introspection type support.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Wed Sep 24 2025 Geoffrey Biggs <geoff@openrobotics.org> - 9.3.3-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Geoffrey Biggs <geoff@openrobotics.org> - 9.3.2-2
- Autogenerated by Bloom

* Fri Apr 18 2025 Geoffrey Biggs <geoff@openrobotics.org> - 9.3.2-1
- Autogenerated by Bloom

* Tue Mar 11 2025 Geoffrey Biggs <geoff@openrobotics.org> - 9.3.1-1
- Autogenerated by Bloom

* Tue Mar 04 2025 Geoffrey Biggs <geoff@openrobotics.org> - 9.3.0-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.2.0-1
- Autogenerated by Bloom

* Mon Nov 25 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.1.0-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.0.3-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.0.2-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.0.1-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Geoffrey Biggs <geoff@openrobotics.org> - 9.0.0-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Geoffrey Biggs <geoff@openrobotics.org> - 8.5.0-1
- Autogenerated by Bloom

* Tue Apr 09 2024 Geoffrey Biggs <geoff@openrobotics.org> - 8.4.0-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Geoffrey Biggs <geoff@openrobotics.org> - 8.3.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Geoffrey Biggs <geoff@openrobotics.org> - 8.2.0-2
- Autogenerated by Bloom

